#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using  while loop and write hi in 9 iteration after best school.


count=1
while [ $count -le 10 ]
do
	echo "Best School"
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	((count++))
done
